version: "3.9"
services:
  redis:
    container_name: redis-dev
    image: "redis:alpine"
    ports:
      - "6379:6379"

  zookeeper:
    container_name:
      zookeeper_merge
    image:
      wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name:
      kafka_merge
    image:
      wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka_merge
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZK_SERVER: zookeeper:2181
      ADVERTISED_HOST: kafka_merge
      CONSUMER_THREADS: 5
      BROKER_ID: 1
      ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  mongo:
    container_name: mongo-dev
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: bootcamp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./mongodbdata_dev:/data/db"

  config:
    container_name: config-dev
    build: ../bootcamp-config-service
    ports:
      - "8888:8888"
    restart: always
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL: docker-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/eureka-service/default/main" ]
      interval: 30s
      timeout: 5s
      retries: 5
  
  eureka:
    container_name: eureka-dev
    build: ../bootcamp-eureka-service
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 5s
      retries: 5
  
  gateway:
    container_name: gateway-dev
    build: ../bootcamp-gateway-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  user:
    build: ../bootcamp-user-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  account:
    build: ../bootcamp-account-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  credit:
    build: ../bootcamp-credit-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  product:
    build: ../bootcamp-product-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  account-transaction:
    build: ../bootcamp-account-transaction-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  credit-transaction:
    build: ../bootcamp-credit-transaction-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  account-transfer:
    build: ../bootcamp-account-transfer-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  report:
    build: ../bootcamp-report-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  debit-card:
    build: ../bootcamp-debit-card-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy
  
  debit-card-statement:
    build: ../bootcamp-debit-card-statement-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  yanki:
    build: ../bootcamp-yanki-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy

  yanki-transaction:
    build: ../bootcamp-yanki-transaction-service
    restart: on-failure
    depends_on:
      eureka:
        condition: service_healthy
